#!/bin/sh

set -u

exec ucode -e 'import { ruleset_download_required_start } from "shinra.ruleset"; let result = ruleset_download_required_start("shinra-ruleset-sync-job", {}); if (!result || result.ok != true) die("failed to start Rule Set sync");'
